// Chapter 21 (Changing Case)

// 1
var allLower = userInput.toLowerCase();

// 2
var x = "I love Pakistan.";
x = x.toLowerCase();
console.log(x);

// 3
var y = "I love Pakistan.";
y = y.toUpperCase();

//
var y = "I love Pakistan.";
var z = y.toLowerCase();
// 5
var arr = ["JKL", "GHI", "DEF", "ABC"];
for (var i = 0; i <= arr.length; i++) {
  var arr2 = arr[i].toLowerCase();
}
// 6
var city = "karachi";
alert(city.toUpperCase());

// 7
var cityName = "kaRacHi";
cityName =
  cityName.slice(0, 1).toUpperCase() + cityName.slice(1, 7).toLowerCase();
console.log(cityName);

// Chapter 22 - 25 (Strings)

/*1. "captain" has been assigned to variable “sameWords”. You want
to slice "ap" out of it.*/
var sameWords = "captain";
sameWords = sameWords.slice(1, 3);
console.log(sameWords);

/*2. The number of characters in the string will be assigned to the
variable.*/
var abc = "1,2,3,4";

/*3. The string "elephant" has been assigned to the variable animal.
Slice the four middle characters out of the string and assign it to
the variable seg, which hasn't been declared beforehand.*/
var animal = "elephant";
var seg = animal.slice(2, 6);
console.log(seg);

/*4. Find the number of characters in the string represented by a
variable and assign the number to a second variable.*/

/*5. In a first statement measure how many characters there are in a
string represented by a variable. In a second statement slice all
but the first character and last 3 characters of the string and
assign it to a second variable that hasn't been declared
beforehand.*/

/*6. var text = "To be or not to be.";
var indx = text.indexOf("be");
What is the value of indx?*/

/*7. var text = "To be or not to be.";
var indx = text.lastIndexOf("be");
What is the value of indx?
Note: Try the above both examples by yourself.*/

/*8. Find the index of the first character of the last instance of "go" in
the string represented by the variable text and assign the number
to the variable indx, which hasn't been declared beforehand.*/

/*9. Code the first line of an if statement that tests whether a segment
with an index represented by indexNum exists in a string.*/

/*10. In this string "abcde", what character is at index 2? (Use
charAt)*/

/*11. Find the 10th character in the string represented by text and
assign it to the variable cha, which hasn't been declared
beforehand.*/

/*12. Find the last character in the string represented by str and
assign it to x, which hasn't been declared beforehand.*/

/*13. Find the the 5th character in a string represented by input
and assign it to cha, which hasn't been declared beforehand.*/

/*14. Code the first line of an if statement that tests whether the
3rd character of a string represented by a variable is a particular
character.*/

/*15. Code a for loop that cycles through all the characters of a
string represented by a variable and assigns each character to an
element of an array that has been declared beforehand.
In the string represented by reply replace the first instance of "no"
with "yes" and assign the revised string to revisedReply, which hasn't
been declared beforehand.*/

/*16. In a string represented by str replace the first instance of "1"
with "one" and assign the revised string to newStr, which hasn't
been declared beforehand.*/

/*17. If you want all instances replaced, enter 3 characters that
need to appear in this statement.
var y = x.replace("a", "z");*/

// Chapter 26 (Rounding Numbers)

/*1. Form a statement that rounds a number to the nearest integer.
 */
var num = 9.65;
num = Math.ceil(num);
console.log(num);

/*2. Round up a number represented by origNum and assign it to
roundNum, which hasn't been declared beforehand.
*/
var num = 9.05;
var roundNum = Math.floor(num);

/*3. Round down a number represented by origNum and assign it to
roundNum, which hasn't been declared beforehand.
*/
var num = 9.05;
var roundNum = Math.floor(num);

/*4. Round a number represented by a variable and assign the result
to a second variable that hasn't been declared beforehand.
*/
var num = 9.65;
var roundNum = Math.round(num);

/*5. Round .5 to 0 and assign it to a variable that hasn't been declared
beforehand.
*/
var num = 0.5;
var roundNum = Math.trunc(num);

// Chapter 27 (Random Numbers)
/*1. Convert a random number generated by JavaScript to a number in
the range 1 to 50
*/
var num = Math.floor(Math.random() * 50);

/*2. Generate a random number and assign it to a variable that hasn't
been declared beforehand.
*/

var num = Math.floor(Math.random() * 50);

/*3. You have to create a dice in JavaScript with the use of pseudo-
random number.
*/
function rolldice() {
  console.log(Math.floor(Math.random() * 6) + 1);
}

/*4. You have to create a toss (head/tail) in JavaScript with the use of
pseudo-random number.
*/
var num = Math.ceil(Math.random() * 1);
console.log(num);
if (num == 0) {
  console.log("You opt a head");
} else {
  console.log("You opt a tail");
}
// Chapter 28, 29 (Converting Strings)
/*1. How do you convert a string to an integer in JavaScript?
 */
var num=parseInt("2");
/*2. Write a JavaScript function to convert the string "123" to an
integer.
*/
var num="123"
function numConversion(num){
num=parseInt(num);
console.log(num);
}
numConversion(num);
/*3. How can you convert a string containing a decimal number to a
floating-point number in JavaScript?
*/
var num="123.45";
num=parseFloat(num);
/*4. How can you check if a string can be successfully converted to an
integer or decimal in JavaScript before performing the
conversion?
*/
//by doing console.log
/*
5. How can you convert a number to a string in JavaScript?
*/
//by toString() method
/*
6. Write a JavaScript function to convert the number 42 to a string.
*/
var numString=42;
numString=numString.toString();
console.log(numString);
/*7. Can you convert a string representing a decimal number (e.g.,
"3.14") to an integer in JavaScript? If so, how?
*/
var decString="3.14";
decString=parseInt(decString);


// Chapter 30 (Controlling the length of decimals)
  
  /*1. Code a statement that rounds a number represented by num to 4
  places, converts it to a string, and assigns it to newNum, which
  hasn't been declared beforehand.*/
  var num=3.1423456789;
  var newNum=num.toFixed(4).toString();
  console.log(newNum);

  /*2. In a single statement round a number represented by a variable to
  2 places, convert it to a string, convert it back to a number, and
  assign it to the same variable. */

  var num=3.1432222.toFixed().toString();
  console.log(num);
  num=+(num);
  console.log(num);
  
  
  /*3. Code the first line of an if statement that tests whether the
  number represented by num, rounded to 2 digits and converted
  to a string, has more than 4 characters in it.*/
 if(num.toFixed(2).toString().length>4){

 }

  /*4. Assign a number with many decimal places to a variable.
  Code an alert that displays the number rounded to 2 decimal
  places and converted to a string.*/
  var num=3.143333322222224444444;
  alert(num.toFixed(2).toString());

  // Chapter 31 - 34 (Date & Time)
  
  /*1. Code a statement that creates a new Date object and assigns it to
  dObj, which hasn't been declared beforehand.*/
var dObj=new Date();

 /* 2. Code a statement that creates a new Date object, converts it to a
  string, and assigns the string to dStr, which hasn't been declared
  beforehand.*/
  var dObj=new Date();
  dStr=dObj.getDate().toString();

  /*3. Code a statement that extracts the day of the week from a Date
  object represented by d and assigns it to day, which hasn't been
  declared beforehand.*/
  var 

/*4. The day has been extracted from the Date object and assigned to
  d. The names of the days of the week have been assigned to the
  array dayNames. Alert the current day with array index.
/*5. Extract all parts of the Date and Time and assign it to the variable
  which has not been declared beforehand.
/*6. Code a statement that creates a Date object for the last day of the
  last month of 2020 and assigns it to later, which hasn't been
  declared beforehand.
 /* 7. Create a Date object for the second day of the second month of
  1992 and assign it to a variable that hasn't been declared
  beforehand.
  
 /* 8. Code a single statement that displays in an alert the milliseconds
  that elapsed between the reference date and the beginning of
  1980.
 /* 9. How do you change the year of a date in JavaScript?
 /* 10. Write a JavaScript function to change the month of a given
  date to January.
/*11. What is the method to change the day of the week for a
  specific date in JavaScript?
 /* 12. Write a JavaScript function to change the minutes of a given
  time to a specific value. (Value by prompt)
/*13. Write a JavaScript function to add a specific number of
  hours to a given time.
/*14. You have to create a age calculator in JavaScript.
  Chapter 35 - 37 (Functions)
  
/*1. Code the first line of a function displayAlert.
 /* 2. Code a function named askName that prompts the user to "Enter
  name" and assigns the answer to userName, which hasn't been
  declared beforehand.
/*3. Code a function that calls 2 other functions.
 /* 4. Code a function that displays a prompt, "Enter name" and then
  displays the name in an alert. Call the function.
 /* 5. Code the first line of a function named concat that has 3
  parameters, the first three letters of the alphabet. Call that takes
  a variable, a string, and a number as arguments.
 /* 6. Code a function that has 2 parameters. Concatenate them and
  assign the result to a variable that hasn't been declared
  beforehand.
  
/*7. Code a function that has three parameters. Multiply them and
  assign them to a variable that hasn't been declared yet.
/*8. Write a JavaScript function that takes an array of numbers as
  input and returns the average of those numbers.
 /* 9. Write a JavaScript function that takes two parameters and returns
  their sum.
  /*10. Write a JavaScript function that takes an array of numbers as
  input and returns the average of those numbers.
 /* 11. You have to capture the returned value from a function and
  store it in a variable?
  /*12. Write a function which tells letter counts of (word).
  /*14. Write a function which tells the age of a person who Born on
  (dateOfBirth)
  /*15. Write a function which tells the presense of (word) in an
  array = ['zaid','haris','raza','abubakar','hassan','hussain','fatima']
  result should be in true or false*/
  var str=prompt("Enter name");
  var array = ['zaid','haris','raza','abubakar','hassan','hussain','fatima']
  var bol=true;
  function match(){
    for(var i=0;i<=array.length;i++){
      if(array[i]==str){
          bol=true;
        console.log(bol);
          break;
      }
      else{
        bol=false;
        console.log(bol);
      }
    }
  }
match();
  
  /*16. Write a function which repeat (letter) 10 times.
  Hint: "abcde" str.repeat(10)*/
var str="abcde ";
function repeat(){
  console.log(str.repeat(10));
}
repeat();

/*17. write a function which reverse array = ['a','b','c','d','e']
  Hint: arr.reverse().*/
  function reverse(){
    var j=5;
    var array = ['a','b','c','d','e'];
    array=array.reverse();
    for(var i=0; i<=array.length;i++){
console.log(array[i]);
    }
  }
  reverse();

  // Chapter 38 (Local vs. GlobalVariables)
  
  /*1. Write a JavaScript function that demonstrates the usage of a local
  variable.*/
  function abc(){
    var a="123";
    console.log(a);
  }

  /*2. How can you access a global variable inside a function in
  JavaScript?*/
  var b=123
  function abc(){
  var a="123";
    console.log(a);
    console.log(b);
  }
  // Chapter 39, 40 (Switch Statements)
  /*1. Write a JavaScript switch statement that checks the value of a
  variable and performs different actions based on different cases.
  */
    var cityName=["Karachi","Lahore"];
    switch(cityName){
      case "Karachi":
        console.log(1)
      case "Lahore":
        console.log(2);
    }

  /*2. Write a JavaScript switch statement that check whether cityName
  given by user check the cityName if match alert the user and
  break the statement, if not default message will be shown to user.*/
    var cityName=["Karachi","Islamabad","Faislabad","Lahore"];
    switch(cityName){
      case "Karachi":
        alert("exist");
      case "Faislabad":
        alert("exist");
          
      case "Lahore":
        alert("exist");
          
      case "Islamabad":
        alert("exist");
      default:
        alert("Not exist");    
    }
  
  // ================= THE END =================